id = "sonokai"
name = "Sonokai"
version = "0.0.7"
schema_version = 1
authors = ["ciathefed <ciathefed@protonmail.com>"]
repository = "https://github.com/ciathefed/zed-sonokai"
description = "Sonokai Color Scheme for Zed"
